// <auto-generated />
namespace TrainBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EnhanceTrainSeatTypeModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnhanceTrainSeatTypeModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202209171906080_EnhanceTrainSeatTypeModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
