// <auto-generated />
namespace TrainBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EnchanceTrainAndRouteEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnchanceTrainAndRouteEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202209171208141_EnchanceTrainAndRouteEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
